services:
  ftp:
    build: ./ftp
    container_name: ftp-ctf
    ports:
      - "21:21"      
      - "30000-30009:30000-30009"
    networks:
      - ctf-network

networks:
  ctf-network:
    driver: bridge